#!/bin/bash

# This pbuilder hook is executed after a pbuidler environment create/update.
# so we can modify the chroot environment.
#
# for this hook to be picked up, HOOKDIR variable should be set in pbuilderrc
# file, or --hookdir should be passed to pbuilder
#
# see:
# https://manpages.debian.org/testing/pbuilder/pbuilder.8.en.html (--hookdir)
# https://wiki.ubuntu.com/PbuilderHowto#Using_backport_repositories_in_pbuilder

DIST="$DISTRIBUTION"  # DISTRIBUTION is passed by pbuilder

# @TODO: support Debian backports if not on Ubuntu
echo "Ensuring golang backports PPA ..."
apt-get update; apt-get install -yq software-properties-common
add-apt-repository ppa:longsleep/golang-backports; apt-get update



